### ISSUE TITLE
Picture seems to be disappeared

### ISSUE THREAD

**Issue by LLinVIP** [zyuanx/cumtddnet#2]
Thanks for your work! Could you possibly let me know if the code can work fine now? And, pictures in Readme seems to be disappeared.

**Comment by zyuanx** [comment]
Hi, I have graduated for several years. You can try to run the code on your computer, or try to modify it, I guess it should be usable.

**Comment by LLinVIP** [comment]
> 

Thanks for reply. Wish you have a bright future.
